### ISSUE TITLE
Call to end() does not close connection on node 0.12

### ISSUE THREAD

**Issue by ilya-kosolapov** [mscdex/node-imap#452] opened 2015-02-18 17:32 UTC
Works fine on node 0.10.36.

Test script:
```javascript
var Imap = require('imap');

var imap = new Imap({
	debug: console.log,
	user: '*******@*****.**',
	password: '********',
	host: '******',
	port: 993,
	tls: true,
	tlsOptions: {rejectUnauthorized: false}
});

imap.once('ready', function() {
	imap.end();
});

imap.connect();
```

On node 0.10.36, this scripts exits right away after connecting. On node 0.12, it hangs. The debug messages are the same with the exception of `[connection] Closed` logged last after `<= 'A4 OK Logout completed.'` on 0.10, but not on 0.12.

This is connecting to dovecot 2.2.15-2/postfix 2.11.3-2 on arch linux.

**Comment by sergenikitin** [comment] 2015-02-27 09:54
I have same bug on io.js. It hangs.

To close script I use 
```
imap.closeBox(() => {
                        imap.destroy();
                        imap.end();
                    });
```

**Comment by devotis** [comment] 2015-03-09 16:10
Me too. Solution by @sergenikitin for 0.12 works

**Comment by devotis** [comment] 2015-03-13 12:08
Solution is to add to the config of the imap connection `keepAlive: false`. It's true [by default](https://github.com/mscdex/node-imap/blob/98200e0b3f8cae683b213482a926666a0d3c9d9e/lib/Connection.js#L73).

It's used for the [socket keepAlive](https://github.com/mscdex/node-imap/blob/98200e0b3f8cae683b213482a926666a0d3c9d9e/lib/Connection.js#L102) that probably never ends because of this. And so the [imap connection doesn't end](https://github.com/mscdex/node-imap/blob/98200e0b3f8cae683b213482a926666a0d3c9d9e/lib/Connection.js#L184).

**Comment by testpossessed** [comment] 2015-06-13 10:07
Following the link to the code for the Connection I can see that keepAlive should be keepalive.  However this solution still doesn't work for me.  The end event on the connection never gets emitted.

**Comment by hasenstein** [comment] 2015-07-16 15:53
I have a new twist: (using io.js 2.3.4 but that should make no difference):

When I call `imap.end()` on "ready" the process exits just fine. But when I use the wrong credentials so that I get an "error" upon `imap.connect()` I can try anything from doing nothing to `imap.end()` and/or `imap.destroy()` but the process hangs. I have to `throw err;` to make it stop which should not be necessary.

**Comment by hasenstein** [comment] 2015-07-16 16:26
I found a fix -- for my issue, this is probably the same for the original bug report too, only in other places:

    self._sock.destroy()

does not seem to end the connection. I changed function `reentry` and added `self._sock.end();` (deliberately before the `emit`):

      var reentry = function(err) {
        clearTimeout(self._tmrAuth);
        if (err) {
          self._sock.end();  // THIS IS NEW
          self.emit('error', err);
          return self._sock.destroy();
        }

**Comment by mscdex** [comment] 2015-07-16 17:05
I'd accept a PR to replace `_sock.destroy()` with `_sock.end()`.

**Comment by hasenstein** [comment] 2015-07-16 18:44
It's just two lines that I even linked to, you as the owner can edit it right in github. Do I really have to clone the repository and create a patch for two lines?

**Comment by mscdex** [comment] 2015-07-16 18:53
Just thought I'd let someone take credit for it, but I can fix it myself ...

**Comment by mscdex** [comment] 2015-07-16 18:55
Landed in 1745b22f25.

**Closed by mscdex** 2015-07-16 18:55 UTC

**Comment by hasenstein** [comment] 2015-07-16 18:57
For reference - my posting on the node.js mailinglist: https://groups.google.com/forum/#!topic/nodejs/S6BzCrSyO68

**Comment by generalredneck** [comment] 2015-08-19 20:51
Anyone else still having this issue? I am with node 0.12.5 and imap 0.8.15 where doing imap.destroy(); imap.end() does not call the end event.

**Comment by TimeForAChange** [comment] 2015-08-19 21:43
My issue went away with the fix.

**Comment by shaunxu** [comment] 2015-10-21 07:54
I still has the problem with Node v0.12.7 and node-imap v0.8.15. When I executed ```imap.end();```, the ```end``` event was not emitted.

I can see the code ```Connection.prototype.end()``` was executed and the procedure ```elf._sock.end()``` was executed, too. But ```socket.once('end', function() { ... })``` was not fired somehow.

I noticed in ```connect()``` function there's a statement ```socket.setKeepAlive(true)```, which might cause the TCP connection was remained after called ```end()```. But after commented this line of code ```end``` event still not fired.

**Comment by mscdex** [comment] 2015-10-21 15:51
@shaunxu Are you able to try with a newer version of node, such as v4.2.1? I'm wondering if this is just a node v0.12 thing...

**Comment by shaunxu** [comment] 2015-10-22 01:55
@mscdex I confirmed it works with node v4.2.1 but failed (I means not 'end' event emitted) under v0.12. But in my project I have to use node v0.12 as one of the dependency (node-contextify) doesn't work with the latest version of node.

**Comment by NamTThai** [comment] 2016-04-20 21:25
Any update on this issue? I also encounter the same problem on node-v4.4.3

**Comment by mscdex** [comment] 2016-04-20 21:28
@NamTThai Can you post debug output (set `debug: console.log` in the connection config)?

**Comment by NamTThai** [comment] 2016-04-20 21:47
@mscdex oops false alarm, I tested it on the wrong system. Confirmed this seems to be only a v0.12 thing

**Comment by mscdex** [comment] 2016-04-20 22:08
FWIW at this point since it seems like this is v0.12-specific (which suggests to me that this was a bug/regression) and v0.12 (already in maintenance only mode) support ends this year, I am not sure it is worth investigating a workaround for v0.12.
